[package]
name = "pally_aura"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.16.0", features = [
  "file_watcher",
  "jpeg",
  "dynamic_linking",
] }

bevy_panorbit_camera = { git = "https://github.com/aloucks/bevy_panorbit_camera", branch = "bevy-0.16" }
