[package]
name = "pally_aura"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.0", features = [
  "file_watcher",
  "jpeg",
  "dynamic_linking",
] }

shadplay = { path = "../../shadplay" }
